### ISSUE TITLE
Can the extension access the AsyncStorage of main application ? 

### ISSUE THREAD

**Issue by shishircc** [alinz/react-native-share-extension#21]
In my app, to minimize the latency, I want to display options based on data in main application's async storage. Is that possible ? 

How does the main application share data with extension ? Things like userid etc.

**Comment by alinz** [comment]
@shishircc, No, Share Extension have no access to main app, even thought they are bundle together. I have created a new project called [react-native-swiss-knife](https://github.com/alinz/react-native-swiss-knife) which created a pipe between share and main app. Take a look at the Bucket api inside that project. You don't have to use it but this is what I'm doing for sharing data between them.

**Comment by shishircc** [comment]
Thanks !

**Comment by npomfret** [comment]
You can use a shared filesystem.  With iOS app groups can share a directory where you could store your database.  I've recently had a PR accepted to react-antive-fetch-blob that adds a function which will return the name of the shared directory for a given app group.

**Comment by benjie** [comment]
I just used https://github.com/oblador/react-native-keychain to share credentials between the share extension and the main app; there's two important things to note:

1. react-native-keychain defaults to a "service" of the identifier of the app, which differs between the app and the extension. Thus you must explicitly set them to be the same via the `service` option. (Took me longer than I'd like to admit to figure this out.)
2. you should set the Keychain Access Groups in both the app and the extension to be an array with just one value which should be the exact same string, which should be prefixed with `$(AppIdentifierPrefix)`.

**Comment by parkerdan** [comment]
@benjie, can you please explain more on how you go this to work?  I am trying to share data from the main app the the share extension with `react-native-keychain` and I keep getting `false` when calling the `getGenericPassword` on the share extension...

**Comment by benjie** [comment]
Sorry, that’s all I remember. I do remember expecting some things to be the same but they turned out to differ and that was the issue ultimately (though I don’t remember which thing that was); I suggest you look at each of the values I have mentioned in the compiled app and see where the disparity lies. Good luck!

**Comment by parkerdan** [comment]
@benjie, thanks anyways.

FYI, I have this working and can put together a tutorial if anyone gets to this message and needs clarification.  I have only developed iOS so far, but the goal is both platforms

**Comment by pkantsedalov** [comment]
@parkerdan 
Please share the tutorial with me in any way preferable for you.

**Comment by jvandenaardweg** [comment]
Just found this issue here when I was struggling with the same. I got it working by the steps described below. Hope this helps others!

Bundle Identifier used in this example: `com.example.appname`

1. Make sure you have a App Group set up in your main App and Extension. They need to have the same name, for example: `group.appName`

2. Make sure your main App and Extension have "Keychain Sharing" enabled. The Keychain Group need to be the same, for example: `keychainGroup`.

3. Then, use the method's like this:
```javascript
await Keychain.getGenericPassword({ accessGroup: 'group.appName', service: 'com.example.appname' });

await Keychain.setGenericPassword('token', token, { accessGroup: 'group.appName',  service: 'com.example.appname' });
```

The `service` option seem to be required in this use case with an extension.

Thanks @benjie for pointing that out.
